#!/usr/bin/env bash
set -e

case $(os_type) in
mac)
  ;;
linux) # ubuntu
  #* vim(tiny) not support system paste/copy, using vim-gnome instead
  which vim >/dev/null || sudo apt-get -y install vim-gnome && echo Installing vim-gnome ...
  which ctags >/dev/null || sudo apt-get -y install exuberant-ctags && echo Installing exuberant-ctags ...
  ;;
*)
  ;;
esac

dotfile=$(readlink -f $(dirname $0))/dot.vimrc

echo == use vundle to manage vim plugin
[ -d ~/.vim/bundle ] || { 
  mkdir -p ~/.vim/bundle
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
}

ln -sb $dotfile ~/.vimrc && echo Make a link ~/.vimrc to $dotfile
vim +BundleInstall +qall
echo ==Has set vim
